//===----------------------------------------------------------------------===//
//                         DuckDB
//
// function/scalar/generic_functions.hpp
//
//
//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_functions.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/function/function_set.hpp"

namespace duckdb {

struct ConstantOrNullFun {
	static constexpr const char *Name = "constant_or_null";
	static constexpr const char *Parameters = "arg1,arg2";
	static constexpr const char *Description = "If arg2 is NULL, return NULL. Otherwise, return arg1.";
	static constexpr const char *Example = "constant_or_null(42, NULL)";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

struct GetVariableFun {
	static constexpr const char *Name = "getvariable";
	static constexpr const char *Parameters = "";
	static constexpr const char *Description = "";
	static constexpr const char *Example = "";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

struct ErrorFun {
	static constexpr const char *Name = "error";
	static constexpr const char *Parameters = "message::VARCHAR\001message::VARCHAR,error_type::VARCHAR";
	static constexpr const char *Description = "Throws an Invalid Input Error containing the message.\001Invoke an error containing the message (if applicable). The error type can be 'USER', 'INTERNAL', 'FATAL', 'SIGNAL_SIGSEGV', 'SIGNAL_SIGABRT', or 'SIGNAL_SIGBUS'.";
	static constexpr const char *Example = "error('my_message')\001error('my_fatal_message', 'FATAL')";
	static constexpr const char *Categories = "\001";

	static ScalarFunctionSet GetFunctions();
};

struct CreateSortKeyFun {
	static constexpr const char *Name = "create_sort_key";
	static constexpr const char *Parameters = "parameters...";
	static constexpr const char *Description = "Constructs a binary-comparable sort key based on a set of input parameters and sort qualifiers";
	static constexpr const char *Example = "create_sort_key('A', 'DESC')";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

} // namespace duckdb
