//===----------------------------------------------------------------------===//
//                         DuckDB
//
// core_functions/scalar/debug_functions.hpp
//
//
//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_functions.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/function/function_set.hpp"

namespace duckdb {

struct VectorTypeFun {
	static constexpr const char *Name = "vector_type";
	static constexpr const char *Parameters = "col";
	static constexpr const char *Description = "Returns the VectorType of a given column";
	static constexpr const char *Example = "vector_type(col)";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

struct SleepMsFun {
	static constexpr const char *Name = "sleep_ms";
	static constexpr const char *Parameters = "milliseconds";
	static constexpr const char *Description = "Sleeps for the specified number of milliseconds and returns NULL";
	static constexpr const char *Example = "sleep_ms(100)";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

struct ChaosExceptionFun {
	static constexpr const char *Name = "chaos_exception";
	static constexpr const char *Parameters = "message,type";
	static constexpr const char *Description = "Throws an exception of the given type with the given message";
	static constexpr const char *Example = "chaos_exception('hello world', 'OUT_OF_MEMORY')";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

struct ChaosSignalFun {
	static constexpr const char *Name = "chaos_signal";
	static constexpr const char *Parameters = "signal";
	static constexpr const char *Description = "Throws the given signal";
	static constexpr const char *Example = "chaos_signal('SIGSEGV')";
	static constexpr const char *Categories = "";

	static ScalarFunction GetFunction();
};

} // namespace duckdb
